name: Build and Deploy to Azure Blob

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site with Eleventy
        run: npm run build

      - name: Deploy to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            # Delete all existing blobs in $web container
            az storage blob delete-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --source '$web' \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}
            
            # Upload all files fresh
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source ./_site \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}

      - name: Purge Bunny CDN Cache
        run: |
          curl --location --request POST 'https://api.bunny.net/pullzone/4346060/purgeCache' \
            --header 'AccessKey: ${{ secrets.BUNNY_CDN_APIKEY }}'